prepare:
	copy MakeFile ".\src"
	copy ".\src\Properties\AssemblyInfo.cs" ".\src"
all: prepare
	make -C src build
build: 
	csc /target:library /r:../lib/Kompas6API5.dll,../lib/KAPITypes.dll,../lib/Kompas6Constants.dll /out:../kompasAddon.dll *.cs
	make clean
clean:
	del AssemblyInfo.cs
	del MakeFile